version: '3'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    labels:
      description: "Portaniner: Web interface to manage docker containers"
      system: true
    volumes:
      - /data/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - system
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  system:
    driver: bridge

