logoutput: split
loglevel: debug
datafile: /boot/config/parameters.yml

# Destinations
etc: &etc /etc
boot: &boot /boot
data: &data /data
local: &local /usr/local

process:
- source: /boot/config/data
  operations:
  - destination: *data
    regex: '.*\.template'
  - destination: *data
    template: false
- source: /boot/config/local
  operations:
  - destination: *local
    template: false
    permissions:
    - mode: "0755"
      glob: '*/bin/*'
    - mode: "0755"
      glob: '*/sbin/*'
- source: /boot/config/scripts/final
  operations:
  - destination: /tmp/confinit
    template: true
    delextension: false
    default:
      mode:
        file: "0755"
    command:
      cmd: ["{{.Destination}}"]

